[INFO]  2019-05-12 18:52:55 appium_port.py[line:17] : port 4725 is Availible!
[INFO]  2019-05-12 18:52:55 appium_port.py[line:17] : port 4723 is Availible!
[INFO]  2019-05-12 18:54:21 appium_port.py[line:17] : port 4725 is Availible!
[INFO]  2019-05-12 18:54:21 appium_port.py[line:17] : port 4723 is Availible!
[INFO]  2019-05-12 18:54:21 multi_devices_sync.py[line:34] : appium port : 4723 start run 127.0.0.1:62001 at 2019-05-12 18:54:21 
[INFO]  2019-05-12 18:54:21 multi_devices_sync.py[line:34] : appium port : 4725 start run 127.0.0.1:62025 at 2019-05-12 18:54:21 
[ERROR]  2019-05-12 18:54:26 multi_devices_sync.py[line:41] : appium port : 4723 start Failed 127.0.0.1:62001 at 2019-05-12 18:54:26 
[ERROR]  2019-05-12 18:54:26 multi_devices_sync.py[line:41] : appium port : 4725 start Failed 127.0.0.1:62025 at 2019-05-12 18:54:26 
[INFO]  2019-05-12 18:59:03 appium_port.py[line:21] : port 4723 is Used!
[INFO]  2019-05-12 18:59:03 appium_port.py[line:21] : port 4725 is Used!
[INFO]  2019-05-12 18:59:03 appium_port.py[line:40] : port 4723 is release Success!
[INFO]  2019-05-12 18:59:03 appium_port.py[line:40] : port 4725 is release Success!
[INFO]  2019-05-12 18:59:03 multi_devices_sync.py[line:34] : appium port : 4723 start run 127.0.0.1:62001 at 2019-05-12 18:59:03 
[INFO]  2019-05-12 18:59:03 multi_devices_sync.py[line:34] : appium port : 4725 start run 127.0.0.1:62025 at 2019-05-12 18:59:03 
[ERROR]  2019-05-12 18:59:03 multi_devices_sync.py[line:41] : appium port : 4723 start Failed 127.0.0.1:62001 at 2019-05-12 18:59:03 
[ERROR]  2019-05-12 18:59:03 multi_devices_sync.py[line:41] : appium port : 4725 start Failed 127.0.0.1:62025 at 2019-05-12 18:59:03 
[INFO]  2019-05-12 19:02:30 appium_port.py[line:21] : port 4723 is Used!
[INFO]  2019-05-12 19:02:30 appium_port.py[line:21] : port 4725 is Used!
[INFO]  2019-05-12 19:02:31 appium_port.py[line:40] : port 4723 is release Success!
[INFO]  2019-05-12 19:02:31 appium_port.py[line:40] : port 4725 is release Success!
[INFO]  2019-05-12 19:31:13 myUnittest.py[line:18] : ====== setUp ======
[INFO]  2019-05-12 19:31:13 myUnittest.py[line:25] : ====== tearDown ======
[INFO]  2019-05-12 19:34:27 myUnittest.py[line:18] : ====== setUp ======
[INFO]  2019-05-12 20:48:02 myUnittest.py[line:13] : ====== setUp ======
[INFO]  2019-05-12 20:48:02 myUnittest.py[line:13] : ====== setUp ======
[INFO]  2019-05-12 20:48:02 myUnittest.py[line:13] : ====== setUp ======
[INFO]  2019-05-12 20:48:02 myUnittest.py[line:13] : ====== setUp ======
[INFO]  2019-05-12 20:48:02 myUnittest.py[line:13] : ====== setUp ======
[INFO]  2019-05-12 20:48:02 myUnittest.py[line:13] : ====== setUp ======
[INFO]  2019-05-12 20:48:02 myUnittest.py[line:13] : ====== setUp ======
[INFO]  2019-05-12 20:48:02 myUnittest.py[line:13] : ====== setUp ======
[INFO]  2019-05-12 20:49:22 myUnittest.py[line:13] : ====== setUp ======
[INFO]  2019-05-12 20:49:24 myUnittest.py[line:18] : ====== tearDown ======
[INFO]  2019-05-12 20:49:32 myUnittest.py[line:13] : ====== setUp ======
[INFO]  2019-05-12 20:49:32 myUnittest.py[line:18] : ====== tearDown ======
[INFO]  2019-05-12 20:49:40 myUnittest.py[line:13] : ====== setUp ======
[INFO]  2019-05-12 20:49:40 myUnittest.py[line:18] : ====== tearDown ======
[INFO]  2019-05-12 20:49:48 myUnittest.py[line:13] : ====== setUp ======
[INFO]  2019-05-12 20:49:48 myUnittest.py[line:18] : ====== tearDown ======
[INFO]  2019-05-12 22:51:42 appium_port.py[line:17] : port 4723 is Availible!
[INFO]  2019-05-12 22:51:42 appium_port.py[line:17] : port 4725 is Availible!
[INFO]  2019-05-12 22:51:42 multi_devices_sync.py[line:34] : appium port : 4723 start run 127.0.0.1:62001 at 2019-05-12 22:51:42 
[INFO]  2019-05-12 22:51:42 multi_devices_sync.py[line:34] : appium port : 4725 start run 127.0.0.1:62025 at 2019-05-12 22:51:42 
[INFO]  2019-05-12 22:52:10 multi_devices_sync.py[line:37] : ====== start run app ======
[INFO]  2019-05-12 22:56:15 appium_port.py[line:21] : port 4723 is Used!
[INFO]  2019-05-12 22:56:15 appium_port.py[line:21] : port 4725 is Used!
[INFO]  2019-05-12 22:56:15 appium_port.py[line:40] : port 4723 is release Success!
[INFO]  2019-05-12 22:56:15 multi_appium.py[line:24] : start /b appium -a 127.0.0.1 -p 4723 -bp 4724 at 2019-05-12 22:56:15
[INFO]  2019-05-12 22:56:15 appium_port.py[line:40] : port 4725 is release Success!
[INFO]  2019-05-12 22:56:15 multi_appium.py[line:24] : start /b appium -a 127.0.0.1 -p 4725 -bp 4726 at 2019-05-12 22:56:15
[INFO]  2019-05-12 22:56:15 multi_devices_sync.py[line:34] : appium port : 4723 start run 127.0.0.1:62001 at 2019-05-12 22:56:15 
[INFO]  2019-05-12 22:56:15 multi_devices_sync.py[line:34] : appium port : 4725 start run 127.0.0.1:62025 at 2019-05-12 22:56:15 
[ERROR]  2019-05-12 22:56:15 multi_devices_sync.py[line:41] : appium port : 4723 start Failed 127.0.0.1:62001 at 2019-05-12 22:56:15 
[ERROR]  2019-05-12 22:56:16 multi_devices_sync.py[line:41] : appium port : 4725 start Failed 127.0.0.1:62025 at 2019-05-12 22:56:16 
